//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.24 at 04:31:58 PM CET 
//


package com.tiarebalbi.sample.geocodingapi.client.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Viewport complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="Viewport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="southwest" type="{http://www.kben.org/google-geocode}Location"/>
 *         &lt;element name="northeast" type="{http://www.kben.org/google-geocode}Location"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Viewport", propOrder = {
  "southwest",
  "northeast"
})
public class Viewport {

  @XmlElement(required = true)
  protected Location southwest;
  @XmlElement(required = true)
  protected Location northeast;

  /**
   * Gets the value of the southwest property.
   *
   * @return possible object is
   * {@link Location }
   */
  public Location getSouthwest() {
    return southwest;
  }

  /**
   * Sets the value of the southwest property.
   *
   * @param value allowed object is
   *              {@link Location }
   */
  public void setSouthwest(Location value) {
    this.southwest = value;
  }

  /**
   * Gets the value of the northeast property.
   *
   * @return possible object is
   * {@link Location }
   */
  public Location getNortheast() {
    return northeast;
  }

  /**
   * Sets the value of the northeast property.
   *
   * @param value allowed object is
   *              {@link Location }
   */
  public void setNortheast(Location value) {
    this.northeast = value;
  }

}
